### PR TITLE
Fixes and remaining components

### PR DESCRIPTION
**Pull request by use-strict**
I cross-checked the contents of my d.ts and integrated them in this pull request. I'm not 100% that everything is correct. There are a few types that I am unsure of. Please ask if there is anything which doesn't add up.

### CODE REVIEW

**Comment by use-strict** [comment]
I propose that all `*Prop` interfaces are renamed to `*Props` for consistency with react definitions.

**Comment by ngbrown** [comment]
@use-strict The changes to react.d.ts were included in this branch, and for components that have methods, I didn't see any other way to handle the ref (except the user being forced to typecast).  Do you have any suggestions?

Running the tests would at least check syntax even if the tests don't exercise them. What errors did you get when running the tests?

**Comment by use-strict** [comment]
Maybe I'm missing something, but I saw you already extend from `React.Props<..>` so it shouldn't be needed to duplicate the `ref` definition. It should correctly inherit it from the base interface.

I didn't run the tests because I got an error straight away in the IDE (VSCode) regarding HTMLAttributesBase<T>, so I assumed the react.d.ts changes were not there.

**Comment by ngbrown** [comment]
@use-strict on the ref definition, it was my way of catching when I was trying to inherit from `React.HTMLAttributes` and not being allowed to redefine the ref (thus the change to react.d.ts).

If you are testing this in your own project maybe you'll have to copy the react.d.ts from this branch.  The DefinitelyTyped tests do work though.

**Pull request merged**
